Dev
java-park-mail-ru/exchange-02-2017 pull request #3
Opened 2017-05-11 12:06 UTC by SCaptainCAP

2017-05-11 12:08 UTC, KSolovyev commented
Добавьте ссылку на фронт в описание пул реквеста

2017-05-14 00:12 UTC, KSolovyev requested changes
будет еще

2017-05-14 00:12 UTC, KSolovyev commented on src/main/java/com/cyclic/configs/Constants.java
> +    public static final int ACTION_READY_FOR_ROOM_SEARCH = 1;
в enum

2017-05-14 00:12 UTC, KSolovyev commented on src/main/java/com/cyclic/configs/Constants.java
> +    public static final int DATATYPE_ROOMINFO = 1;
в enum

2017-05-14 00:12 UTC, KSolovyev commented on src/main/java/com/cyclic/configs/Constants.java
> +    public static final int STATUS_FULL_SMB_NOT_READY = 2;
здесь вообще все выглядит, как enum'ы

2017-05-14 00:12 UTC, KSolovyev commented on src/main/java/com/cyclic/controllers/WebSocketController.java
> +        //System.out.println("errorConsole occured at sender " + session);
комментариев в коде быть не должно

2017-05-14 00:12 UTC, KSolovyev commented on src/main/java/com/cyclic/models/game/GameField.java
> +                world[i][j] = null;
в java массивы автоматически инициализируются null'ами

2017-05-14 00:12 UTC, KSolovyev commented on src/main/java/com/cyclic/models/game/GameField.java
> +            return;
и все? просто забьем?

2017-05-14 00:12 UTC, KSolovyev commented on src/main/java/com/cyclic/models/game/GameField.java
> +    public Point findRandomNullPoint() {
пометьте как `@Nullable`

2017-05-14 00:12 UTC, KSolovyev commented on src/main/java/com/cyclic/models/game/GameField.java
> +        room = null;
и все?

2017-05-14 00:12 UTC, KSolovyev commented on src/main/java/com/cyclic/models/game/GameField.java
> +        }
весь алгоритм выглядит громоздко. Можно лучше

2017-05-14 00:12 UTC, KSolovyev commented on src/main/java/com/cyclic/models/game/GameField.java
> +    private final static Random randomDelta = new Random(); // TODO check
а раньше вы ThreadLocalRandom использовали

2017-05-18 16:05 UTC, SCaptainCAP commented
Исправлены замечания

2017-05-22 12:22 UTC, KSolovyev requested changes

2017-05-22 12:22 UTC, KSolovyev commented on src/main/java/com/cyclic/models/game/GameField.java
> +            Vector<RNode> deleteNodes = new Vector<>();
а почему здесь вектор?

2017-05-22 12:22 UTC, KSolovyev commented on src/main/java/com/cyclic/models/game/Room.java
> +    private transient int performingPlayerIndex;
а зачем помечать их как transient?

2017-05-22 12:22 UTC, KSolovyev commented on src/main/java/com/cyclic/models/game/Room.java
> +                        player.disconnectBadApi("Your are moving like an asshole");
не надо так

2017-05-22 12:22 UTC, KSolovyev commented on src/main/java/com/cyclic/models/game/GameField.java
> +    public MoveBroadcast acceptMove(Player player, Move move) {
move-то у вас nullable. NPE чую я здесь. 
А вообще не очень делать таймаут через нулевой ход. Чувствуется здесь архитектурный косяк, который когда понадобится еще что-нибудь заставит вас очень сильно рефакторить код механики

2017-05-23 09:40 UTC, SCaptainCAP commented on src/main/java/com/cyclic/models/game/GameField.java
> +            Vector<RNode> deleteNodes = new Vector<>();
Потому что метод killNode возвращает специальный класс 
`private class NodesAndLinks`,
содержащий 2 вектора - удаленные вершины и удаленные связи. Эти вектора мы как раз и собираем. Вы имеете ввиду, что лучше заменить их на `ArrayList`?

2017-05-23 09:43 UTC, SCaptainCAP commented on src/main/java/com/cyclic/models/game/GameField.java
> +    public MoveBroadcast acceptMove(Player player, Move move) {
Мы принимаем ходы, отправленные разными игроками. Я посчитал, что Таймер таймаута - это некая сущность, похожая на игрока, который ходит вместо ходящего игрока, но передает "Никакой" ход. Так что это фича. По крайней мере, я не могу придумать ситуаций, в которых это помешает расширению фишек сервера. Для этого кстати достаточно расширить класс `Move`, добавив в него какие-то новые поля, и парся их уже после проверки хода на null

2017-05-23 09:44 UTC, SCaptainCAP commented on src/main/java/com/cyclic/models/game/Room.java
> +                        player.disconnectBadApi("Your are moving like an asshole");
Пофикшено. Хотя, это ускоряло процесс разработки фронтенда

2017-05-23 09:46 UTC, SCaptainCAP commented on src/main/java/com/cyclic/models/game/Room.java
> +    private transient int performingPlayerIndex;
Потому что мы используем Gson как сериализатор. Он не сериализует поля, отмеченные `transient`. Так как в последствии мы сериализуем комнату и отправляем ее клиенту, я пометил поля, которые клиенту знать не нужно

2017-05-23 11:10 UTC, KSolovyev commented on src/main/java/com/cyclic/models/game/GameField.java
> +            Vector<RNode> deleteNodes = new Vector<>();
Да, Vector практически не используется нигде

2017-05-23 11:11 UTC, KSolovyev commented on src/main/java/com/cyclic/models/game/GameField.java
> +    public MoveBroadcast acceptMove(Player player, Move move) {
А он может передавать специльный ход, который передает управление следующему игроку?

2017-05-23 13:24 UTC, SCaptainCAP commented on src/main/java/com/cyclic/models/game/GameField.java
> +    public MoveBroadcast acceptMove(Player player, Move move) {
Да, было бы логично. Добавлю сегодня такую реализацию

2017-05-23 13:24 UTC, SCaptainCAP commented on src/main/java/com/cyclic/models/game/GameField.java
> +            Vector<RNode> deleteNodes = new Vector<>();
Хорошо, изменю на ArrayList

2017-05-23 22:06 UTC, SCaptainCAP commented on src/main/java/com/cyclic/models/game/GameField.java
> +    public MoveBroadcast acceptMove(Player player, Move move) {
Реализовано с помощью наследования

2017-05-23 22:07 UTC, SCaptainCAP commented on src/main/java/com/cyclic/models/game/GameField.java
> +            Vector<RNode> deleteNodes = new Vector<>();
Изменено на ArrayList

2017-05-24 08:41 UTC, KSolovyev commented on src/main/java/com/cyclic/models/game/Room.java
> +                        player.disconnectBadApi("Your are moving like an asshole");
я имел в виду сообщение

2017-05-24 08:44 UTC, KSolovyev commented
у меня не получается зарегистрироваться

2017-05-24 08:46 UTC, KSolovyev commented
А, это был ник короткий. Вообще не понятно

2017-05-24 08:50 UTC, KSolovyev commented
А как передать ход другому игроку?

2017-05-24 10:12 UTC, SCaptainCAP commented
Мы выложим сегодня новую версию на Хероку. Та очень сильно устарела. Ошибки логина-регистрации мы уже показываем на новом фронте

2017-05-24 14:20 UTC, SCaptainCAP commented on src/main/java/com/cyclic/models/game/Room.java
> +                        player.disconnectBadApi("Your are moving like an asshole");
Так я тоже :)

2017-05-24 15:21 UTC, KSolovyev commented
отпишитесь, как сделаете

2017-09-18 10:19 UTC, merged